#!/bin/bash

echo "Enter a username: "
read

if [ ${#REPLY} != 0 ]; then
	echo "Username: " >> $1
	echo $REPLY >> $1
else
	echo "Username: " >> $1
	whoami >> $1
fi

echo "Enter a Password: "
read
password="$REPLY"
correct=true

while [ correct ]
do
if [ ${#password} -gt 8 ]; then
	echo "Give your Password again: "
	read
	if [ $REPLY == $password ]; then
		echo "Password= " >> $1
		echo $password | md5sum >> $1
		break
	fi
fi
done